simplify

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -4,13 +4,34 @@ set -e
 
 CDPATH="" cd -- "$(dirname -- "$0")/.."
 
+if [ "$(git rev-parse --is-shallow-repository)" != "false" ]; then
+  echo "script/release cannot be run on a shallow clone"
+  exit 1
+fi
+
 script/bindown -q install goreleaser
+
+git fetch --tags
 
 GITHUB_SHA="${GITHUB_SHA:-"$(git rev-parse HEAD)"}"
 GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-"WillAbides/semver-next"}"
 
-script/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --create-tag --require-labels
+PREV_REF="$(git describe --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null || true)"
+PREV_VERSION="$PREV_REF"
+if [ -z "$PREV_REF" ]; then
+  PREV_REF="$(git rev-list --max-parents=0 HEAD)"
+  PREV_VERSION="0.0.0"
+fi
 
-git fetch --tags
+RES="$(script/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" -p "$PREV_REF" -v "$PREV_VERSION" --json)"
+NEXT_VERSION="$(echo "$RES" | jq -r .next_version)"
+CHANGE_LEVEL="$(echo "$RES" | jq -r .change_level)"
 
+if [ "$CHANGE_LEVEL" = "no change" ]; then
+  echo "No changes since last release"
+  exit 0
+fi
+
+git tag -a -m "v$NEXT_VERSION" "v$NEXT_VERSION"
+git push origin "v$NEXT_VERSION"
 bin/goreleaser release
